on:
  push:
    branches:
      - main

name: Deploy Bookdown

jobs:
  bookdown:
    name: Compile
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-tinytex@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown"))'
      - name: Build HTML
        run: Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
      - name: Build ePub
        run: Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::epub_book')"
      - name: Build PDF
        run: Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"
      - uses: actions/upload-artifact@v1
        with:
          name: Book
          path: _book/
  
  checkout-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: bookdown
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Downoad artifact
        uses: actions/download-artifact@v1
        with:
          name: Book
          path: _book/
      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: _book/
          target-folder: latest
          